name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set image name
      run: echo "IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/docker-react-mysql:latest" >> $GITHUB_ENV

    - name: Show image name
      run: echo "Pushing image to Docker Hub as $IMAGE_NAME"

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME
